### PR TITLE
Update gstwebrtc_app.py

### PR DESCRIPTION
**Pull request by xhrach06**

### CODE REVIEW

**Comment by ehfd** [comment]
@danisla @JanCVanB This is @xhejtman 's student. Added VAAPI and NVFBC.

**Comment by ehfd** [comment]
We are going to hold this and make the code more comprehensible.

**Comment by ehfd** [comment]
For now, review #42 .

**Comment by ehfd** [comment]
To be closed for now. Separate PR for NVFBC.

**Comment by danisla** [comment]
I would prefer this PR to be bundled with the patch to the gstreamer build that adds the `nvfbch264enc` and `nvfbchevcenc` elements.
@xhrach06 do you have the gstreamer patch ready or is it being upstreamed to the gstreamer project?

**Comment by ehfd** [comment]
@danisla
@xhejtman said that this is too premature to be included, of which the patch is separate to the code. Please close for now, `nvfbc` will eventually be included later.

**Comment by GabrieleRisso** [comment]
@ehfd hello, is there any update on including  nvfbc?

**Comment by ehfd** [comment]
Discussed in https://github.com/selkies-project/selkies-gstreamer/issues/30.
@GabrieleRisso
Please ask @xhejtman on [Discord](https://discord.gg/wDNGDeSW5F).

**Pull request closed without merging**
