### PR TITLE
Refactor workflows for maintainability

### PR DESCRIPTION
**Pull request by JanCVanB**

### CODE REVIEW

**Comment by JanCVanB** [comment]
@danisla This is almost done, but can you help me diagnose this GCS failure? https://github.com/selkies-project/selkies-gstreamer/runs/4983911726?check_suite_focus=true
Screen Shot 2022-01-28 at 10 12 31 AM

**Comment by JanCVanB** [comment]
> @danisla This is almost done, but can you help me diagnose this GCS failure?

This was due to incorrect removal of cache reads.

**Comment by JanCVanB** [comment]
@danisla If a `gstreamer` build fails, should we proceed with building the examples (from the latest `gstreamer` builds on GHCR), or should an example build job not trigger if its respective gstreamer build job fails?

**Comment by danisla** [comment]
> @danisla If a `gstreamer` build fails, should we proceed with building the examples (from the latest `gstreamer` builds on GHCR), or should an example build job not trigger if its respective gstreamer build job fails?
> (The latter is the old/current way, so it's likely best, but I just want to confirm.)

We should not trigger if any of the addon images fail.

**Comment by JanCVanB** [comment]
> We should not trigger if any of the addon images fail.

Great, thanks - in the upcoming fixes I'll make the workflow single-threaded, where a job matrix must be all green to proceed to the next job matrix.

**Comment by JanCVanB** [comment]
New release workflow:
Screen Shot 2022-02-03 at 7 03 05 PM

**Comment by JanCVanB** [comment]
@danisla Tests are green, PR looks ready to me!

Workflow(s) for building images (component images, then example images):
Screen Shot 2022-02-03 at 11 35 19 PM

Workflow for publishing release (component images, then example images & asset publishing, then release creation):
Screen Shot 2022-02-03 at 11 34 55 PM

**Comment by JanCVanB** [comment]
@danisla Preliminary testing looks green - running full tests now. I rebased the commits to cut down on noise, but I assume we'll still squash into one commit when this merges. Ready for another review!

**Comment by JanCVanB** [comment]
@danisla Fully green, good to go: https://github.com/selkies-project/selkies-gstreamer/actions/runs/1797002792

**Review by danisla — APPROVED** [review]

**Pull request merged**
